### ISSUE TITLE
Añadir funcionalidad para registrar calendario de partidos

### ISSUE THREAD

**Issue by salvador-barboza** [flimflo/AlpHa#17]

**Comment by genaro56** [comment]
@salvador-barboza me puedes explicar los requerimientos para este plox? Es asignar las fechas de cada partido de la liga? Entonces ocupamos una colección a parte para los calendarios o solamente mostrar las fechas de cada documento de role-table.

**Comment by salvador-barboza** [comment]
solo se necesita mostrar role-table ordenado por fecha
